# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.0.5'


  # Pods for BookList

  target 'BookListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookListUITests' do
    # Pods for testing
  end

end
